src/Project.Web/Controllers/CartController.cs
using AutoMapper;
using Project.Data.Models;
using Project.Service.Services;
using Project.Web.TemporaryMessage;
using Project.Web.ViewModels.Cart;
using Project.Web.ViewModels.Product;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class CartController : BaseController
    {
        private readonly ICartService _cartService;

        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }

        [HttpGet]
        [Authorize]
        public PartialViewResult Index()
        {
            var data =
                new CartIndexViewModel
                {
                    Carts =
                        Mapper.Map<List<CartIndexRowViewModel>>(
                            _cartService
                                .GetCartItems())
                };

            return PartialView("_Index", data.Carts);
        }


        [HttpPost]
        [Authorize]
        public ActionResult Create(ProductDetailsViewModel productDetailsViewModel)
        {
            var productModel = Mapper.Map<ProductModel>(productDetailsViewModel);

            _cartService.Create(productModel);

            SetTemporaryMessage(CartMessage.CartAdded, TemporaryType.Succes);

            return RedirectToAction("Index", "Product");
        }


        [HttpPost]
        [Authorize]
        public PartialViewResult Delete (int id)
        {
            _cartService.Delete(id);

            return Index();
        }
    }
}

src/Project.Web/Controllers/OrderItemController.cs
using AutoMapper;
using Project.Data.Entities;
using Project.Service.Infrastructure.Authorization;
using Project.Service.Services;
using Project.Web.ViewModels.OrderItem;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class OrderItemController : BaseController
    {
        private readonly IOrderItemService _orderItemService;
        private readonly IAuthenticationManager _authenticationManager;

        public OrderItemController(
            IOrderItemService orderItemService,
            IAuthenticationManager authenticationManager)
        {
            _orderItemService = orderItemService;
            _authenticationManager = authenticationManager;
        }

        [Authorize]
        [HttpGet]
        public ActionResult Index() =>
            View();

        [Authorize]
        [HttpGet]
        public ActionResult IndexGrid()
        {
            var user = _authenticationManager.GetUserData();

            var data =
                new OrderItemIndexViewModel
                {
                    Orders = UserRoleEnum.User == (UserRoleEnum)user.UserRoleId
                        ? Mapper.Map<List<OrderItemIndexRowViewModel>>(
                                _orderItemService
                                    .GetOrdersBy(user.Id))
                        : Mapper.Map<List<OrderItemIndexRowViewModel>>(
                                _orderItemService
                                    .GetOrders())
                };

            return PartialView("_IndexGrid", data.Orders);
        }
    }
}

src/Project.Web/Controllers/UserController.cs
using AutoMapper;
using Project.Data.Entities;
using Project.Data.Extensions;
using Project.Data.Models;
using Project.Service.Helper.Serilog;
using Project.Service.Infrastructure.Authorization;
using Project.Service.Services;
using Project.Web.Infrastructure.Role;
using Project.Web.TemporaryMessage;
using Project.Web.ViewModels.User;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IAuthenticationManager _authenticationManager;
        private readonly ILogService _logService;

        public UserController(
            IUserService userService,
            IAuthenticationManager authenticationManager,
            ILogService logService)
        {
            _userService = userService;
            _authenticationManager = authenticationManager;
            _logService = logService;
        }

        [Authorize(Roles = AppRoles.Admin)]
        [HttpGet]
        public ActionResult Index() =>
            View();

        [Authorize(Roles = AppRoles.Admin)]
        [HttpGet]
        public ActionResult IndexGrid()
        {
            var users = new UserIndexViewModel
            {
                Users =
                   Mapper.Map<List<UserIndexRowViewModel>>(
                       _userService
                           .GetUsers())
                           .ToList()
            };

            return PartialView("_IndexGrid", users.Users);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Register() =>
            PartialView("_Register");

        public JsonResult IsEmailExists(string email) =>
            Json(
                !_userService
                    .GetEmails()
                    .Any(x => x.Contains(email)),
                JsonRequestBehavior.AllowGet);

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(UserRegisterViewModel userRegisterViewModel)
        {
            if (ModelState.IsValid)
            {
                var userModelToCreate = Mapper.Map<UserModel>(userRegisterViewModel);
                userModelToCreate.Password = _authenticationManager.HashPassword(userModelToCreate.Password);
                var user = _userService.Create(userModelToCreate);
                SetTemporaryMessage(UserMessage.RegistredSuccessfully, TemporaryType.Succes);
                _logService.Logger.Information("Zarejestrowano uzytkownika : {@user}", user);

                return RedirectToAction("Index", "Product");
            }
            SetTemporaryMessage(UserMessage.RegistrationError, TemporaryType.Danger);
            _logService.Logger.Warning("Nie udało się zarejestrować użytkownika : {@userRegisterViewModel}", userRegisterViewModel);

            return RedirectToAction("Index", "Product");
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Login() =>
            PartialView("_Login");

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserLoginViewModel userLoginViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = _userService.GetUserBy(userLoginViewModel.Email);
                if (user != null)
                {
                    if (user.UserStatusId == UserStatusEnum.NonActive.ToInt())
                    {
                        SetTemporaryMessage(UserMessage.InactiveAccount, TemporaryType.Warning);
                        return RedirectToAction("Index", "Product");
                    }

                    if (user.UserStatusId == UserStatusEnum.Blocked.ToInt())
                    {
                        SetTemporaryMessage(UserMessage.BlockedAccount, TemporaryType.Warning);
                        return RedirectToAction("Index", "Product");
                    }

                    if (_authenticationManager.IsPasswordConfirmed(
                            userLoginViewModel.Password,
                            user.Password))
                    {
                        _authenticationManager.SetAuthenticationToken(user);
                        return RedirectToAction("Index", "Product");
                    }
                }
            }
            SetTemporaryMessage(UserMessage.IncorrectLoginOrPassword, TemporaryType.Warning);
            return RedirectToAction("Index", "Product");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Logout()
        {
            _authenticationManager.Logout();

            return RedirectToAction("Index", "Product");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            id = _authenticationManager.GetLoggedUserId();

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user =
                Mapper.Map<UserEditViewModel>(
                    _userService
                        .GetUserBy(id.Value));

            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(UserEditViewModel userEditViewModel)
        {
            if (!ModelState.IsValid)
                return View(userEditViewModel);

            var userModelToEdit = Mapper.Map<UserModel>(userEditViewModel);

            _userService
                .Edit(userModelToEdit);

            SetTemporaryMessage(UserMessage.UserUpdated, TemporaryType.Succes);
            _logService.Logger.Information("Zaktualizowano uzytkownika : {@user}", userModelToEdit);

            return View(userEditViewModel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditByAdmin(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user =
                Mapper.Map<UserEditByAdminViewModel>(
                    _userService
                        .GetUserBy(id.Value));

            return PartialView("_EditByAdmin", user);
        }

        [HttpPost]
        public ActionResult EditByAdmin(UserEditByAdminViewModel userEditByAdminViewModel)
        {
            var userModelToEdit = Mapper.Map<UserModel>(userEditByAdminViewModel);

            _userService
                .EditByAdmin(userModelToEdit);

            SetTemporaryMessage(UserMessage.UserUpdated, TemporaryType.Succes);
            _logService.Logger.Information("Zaktualizowano uzytkownika : {@user}", userModelToEdit);

            return RedirectToAction("Index");
        }
    }
}

src/Project.Web/Views/Shared/_CarouselSlide.cshtml
<div style="height: 230px; width: auto; margin-bottom: 140px;">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
            <div class="item active">
                <img src="~/Content/image/Shared/1.jpg" alt="Los Angeles" style="height: 350px; width: -webkit-fill-available">
            </div>
            <div class="item">
                <img src="~/Content/image/Shared/2.jpg" alt="Chicago" style="height: 350px; width: -webkit-fill-available">
            </div>
            <div class="item">
                <img src="~/Content/image/Shared/3.jpg" alt="New York" style="height: 350px; width: -webkit-fill-available">
            </div>
        </div>
    </div>
</div>

<a class="left carousel-control" href="#myCarousel" data-slide="prev" style="height: 400px;">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
</a>
<a class="right carousel-control" href="#myCarousel" data-slide="next" style="height: 400px;">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
</a>

src/Project.Web/Views/Shared/_Footer.cshtml
<footer id="sticky-footer" class="py-4 bg-dark text-white-50" style="background-color: #0E76A8; height:70px; opacity:0.9;">
    <div class="container text-center" style="color: #cbcbcb">
        <small>Copyright Bartosz Niedźwiecki</small>
    </div>
</footer>

src/Project.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/MvcGrid/mvc-grid.css")
    @Styles.Render("~/Content/css/common.css")

    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-3.3.1.js")
    @Scripts.Render("~/Scripts/jquery.validate.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.js")
    @Scripts.Render("~/Scripts/app/views/shared/showPopupRegister.js")
    @Scripts.Render("~/Scripts/app/views/shared/showPopupLogin.js")
    @Scripts.Render("~/Scripts/app/views/cart/index/index.js")

</head>
<body>
    @Html.Partial("~/Views/Shared/_Message.cshtml")

    @Html.Partial("~/Views/Shared/_Navbar.cshtml")

    @Html.Partial("~/Views/Shared/_CarouselSlide.cshtml")

    <div class="body-content">
        @RenderBody()
        <hr />
    </div>
    @Html.Partial("~/Views/Shared/_Footer.cshtml")

    @Scripts.Render("~/Scripts/MvcGrid/mvc-grid.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });

    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/Project.Web/Views/Shared/_Message.cshtml
@if (TempData["TemporaryMessage"] != null)
{    
    @Scripts.Render("~/Scripts/app/views/shared/showPopupMessage.js")
}

<div id="modalMessage" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content @TempData["TemporaryType"]" style="background-color: #a2c9db; ">
            <div class="modal-header @TempData["TemporaryType"]" role="alert">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Informacja</h4>
            </div>
            <div class="modal-body">
                <h3>@TempData["TemporaryMessage"]</h3>
            </div>
        </div>
    </div>
</div>

src/Project.Web/Views/Shared/_Navbar.cshtml
@Styles.Render("~/Content/css/app/shared/navbar.css")

<nav class="navbar navbar-inverse navbar-fixed-top navbarBackground" role="navigation">
    <div class="container-fluid">
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "Product")">Strona główna</a></li>
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <li><a href="@Url.Action("Index", "OrderItem")">Zamówienia</a></li>
                }
            </ul>
            @if (HttpContext.Current.User.IsInRole(Project.Web.Infrastructure.Role.AppRoles.Admin))
            {
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "User")">Użytkownicy</a></li>
                </ul>
            }

            @if (HttpContext.Current.User.IsInRole(Project.Web.Infrastructure.Role.AppRoles.Admin))
            {
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Create", "Product")">Dodaj product</a></li>
                </ul>
            }
            <ul class="nav navbar-nav navbar-right">
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <p class="navbar-text">@Html.Label("Witaj:")</p>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                            @HttpContext.Current.User.Identity.Name
                            <span class="glyphicon glyphicon-user"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Edit", "User")">Edytuj <span class="glyphicon glyphicon-edit"></span></a></li>
                            <li><a href="@Url.Action("Logout", "User")">Wyloguj <span class="glyphicon glyphicon-log-out"></span></a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" type="button" id="modalCartButton">Koszyk <span class="glyphicon glyphicon-shopping-cart"></span></a>
                        <div class="modal fade" id="modalCart" role="dialog" data-url="@Url.Action("Index", "Cart")"></div>
                    </li>
                }
                else
                {
                    <li>
                        <a href="#" type="button" id="modalRegisterButton">Rejestracja <span class="glyphicon glyphicon-registration-mark"></span></a>
                        <div class="modal fade" id="modalRegister" role="dialog" data-url="@Url.Action("Register", "User")"></div>
                    </li>
                    <li>
                        <a href="#" type="button" id="modalLoginButton">Logowanie <span class="glyphicon glyphicon-log-in"></span></a>
                        <div class="modal fade" id="modalLogin" role="dialog" data-url="@Url.Action("Login", "User")"></div>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>