src/Project.Web/ViewModels/Category/CategoryIndexViewModel.cs
using System.Collections.Generic;

namespace Project.Web.ViewModels.Category
{
    public class CategoryIndexViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public CategoryIndexViewModel ParentCategory { get; set; }

        public List<CategoryIndexViewModel> Children { get; set; }
    }
}

src/Project.Web/Controllers/CategoryController.cs
using Project.Data.Models;
using Project.Service.Services;
using Project.Web.ViewModels.Category;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var data = GetTreeCategory();
            return PartialView("_Index",data);
        }

        public List<CategoryIndexViewModel> GetTreeCategory() =>
            FillRecursive(_categoryService.GetCategories(), null);

        private List<CategoryIndexViewModel> FillRecursive(List<CategoryModel> categories, int? parentId = null) =>
            categories
                .Where(x => x.ParentId.Equals(parentId))
                .Select(item => new CategoryIndexViewModel
                {
                    Name = item.Name,
                    Id = item.Id.Value,
                    Children = FillRecursive(categories, item.Id)
                })
                .ToList();
    }
}

src/Project.Web/Controllers/ProductController.cs
using AutoMapper;
using Project.Data.Models;
using Project.Service.Helper.Serilog;
using Project.Service.Services;
using Project.Web.Infrastructure.Role;
using Project.Web.TemporaryMessage;
using Project.Web.ViewModels.Product;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly ILogService _logService;

        public ProductController(
            ICategoryService categoryService,
            IProductService productService,
            ILogService logService)
        {
            _categoryService = categoryService;
            _productService = productService;
            _logService = logService;
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Index(int? categoryId)
        {
            IEnumerable<ProductModel> products;

            if(categoryId == null)
                products =
                    _productService
                        .GetProducts();
            else
            {
                var categories =
                    _categoryService
                        .GetCategories();

                var childrenCategoriesId =
                    _categoryService
                        .GetChildrenCategoriesId(
                            categories,
                            categoryId.Value);

                childrenCategoriesId.Add(categoryId.Value);

                products =
                    _productService
                        .GetProductsBy(childrenCategoriesId);
            }

            var data = new ProductIndexViewModel
            {
                Products = Mapper.Map<List<ProductIndexRowViewModel>>(products)
            };

            return View(data.Products);
        }

        [Authorize(Roles = AppRoles.Admin)]
        [HttpGet]
        public ActionResult Create()
        {
            var data = new ProductCreateViewModel
            {
                Category = _categoryService.GetCategories()
            };

            data.Category.Insert(0, new CategoryModel
            {
                Id = null,
                Name = string.Empty
            });

            return View(data);
        }

        [HttpPost]
        public ActionResult Create(ProductCreateViewModel createViewModel, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                var prodcutModel = Mapper.Map<ProductModel>(createViewModel);

                var product =
                    _productService
                        .Create(prodcutModel, Image);

                SetTemporaryMessage(ProductMessage.ProductAdded, TemporaryType.Succes);
                _logService.Logger.Information("Dodano product : {@product}", product);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var data =
                Mapper.Map<ProductDetailsViewModel>(
                    _productService
                        .GetProductBy(id.Value));

            return View(data);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Details(ProductDetailsViewModel productDetailsViewModel)
        {
            if (!ModelState.IsValid)
            {
                var data =
                Mapper.Map<ProductDetailsViewModel>(
                    _productService
                        .GetProductBy(productDetailsViewModel.Id));
                return View(data);

            }

            return View();
        }
    }
}

src/Project.Web/Views/Category/_Index.cshtml
@model IEnumerable<Project.Web.ViewModels.Category.CategoryIndexViewModel>
@{
    ViewBag.Title = "Index2";
}

@Scripts.Render("~/Scripts/app/views/category/index/index.js")
@Styles.Render("~/Content/css/app/category/index.css")

<div class="container">
    <div class="col-md-3">
        <div id="left" class="span3">
            <ul class="nav menu">
                @foreach (var item in Model)
                {
                    <li class="item-1 parent active">
                        <a class="" href="@Url.Action("Index", "Product", new {categoryId = item.Id })">
                            <span data-toggle="collapse" href="#@item.Name" class="sign"><i class="glyphicon-plus"></i></span>
                            <span class="lbl">@item.Name</span>
                        </a>
                    </li>
                    if (item.Children.Any())
                    {
                        @CreateTree(item);
                    }
                }
            </ul>
        </div>
    </div>
</div>

@helper CreateTree(Project.Web.ViewModels.Category.CategoryIndexViewModel item)
{
    <ul class="children nav-child unstyled small collapse" id="@item.Name">
        @foreach (var itemChildren in item.Children)
        {
            if (itemChildren.Children.Any())
            {
                <li class="item-1 parent active">
                    <a class="" href="@Url.Action("Index", "Product", new {categoryId = itemChildren.Id })">
                        <span data-toggle="collapse" href="#@itemChildren.Name" class="sign"><i class="glyphicon-plus"></i></span>
                        <span class="lbl" style="color: #51c3eb">@itemChildren.Name</span>
                    </a>
                </li>
            }
            else
            {
                <li class="item-1">
                    <a class="" href="@Url.Action("Index", "Product", new {categoryId = itemChildren.Id })">
                        <span data-toggle="collapse" href="#@itemChildren.Name" class="sign"><i class="glyphicon-plus"></i></span>
                        <span class="lbl" style="color: #51c3eb">@itemChildren.Name</span>
                    </a>
                </li>
            }

            if (itemChildren.Children.Any())
            {
                @CreateTree(itemChildren);
            }
        }
    </ul>
}