src/Project.Web/ViewModels/Product/ProductCreateViewModel.cs
using FluentValidation;
using FluentValidation.Attributes;
using Project.Core.Infrastructure.AutoMapper;
using Project.Data.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Project.Web.ViewModels.Product
{
    [Validator(typeof(ProductCreateViewModelFluentValidator))]
    public class ProductCreateViewModel
    {
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Pole musi być liczbą")]
        [Display(Name = "Cena")]
        public decimal Price { get; set; }

        [Display(Name = "Opis")]
        public string Description { get; set; }

        [Display(Name = "Zdjęcie")]
        public string Image { get; set; }

        [RegularExpression(@"^\d+$", ErrorMessage = "Pole musi być liczbą")]
        [Display(Name = "Ilość")]
        public int Count { get; set; }

        public int CategoryId { get; set; }

        [Display(Name = "Kategoria")]
        public List<CategoryModel> Category { get; set; }
    }

    public class ProductCreateViewModellProfile : AutoMapperProfile
    {
        public ProductCreateViewModellProfile()
        {
            CreateMap<ProductModel, ProductCreateViewModel>();
            CreateMap<ProductCreateViewModel, ProductModel>();
        }
    }

    public class ProductCreateViewModelFluentValidator : AbstractValidator<ProductCreateViewModel>
    {
        public ProductCreateViewModelFluentValidator()
        {
            RuleFor(r => r.Name)
                .NotEmpty()
                .WithMessage("Pole jest wymagane")
                .MaximumLength(50)
                .WithMessage("Pole może mieć maksymalnie 50 znaków");

            RuleFor(r => r.Price)
                .NotEmpty()
                .WithMessage("Pole jest wymagane");

            RuleFor(r => r.Description)
               .NotEmpty()
               .WithMessage("Pole jest wymagane");

            RuleFor(r => r.Count)
                .NotEmpty()
                .WithMessage("Pole jest wymagane");

            RuleFor(r => r.Image)
                .NotEmpty()
                .WithMessage("Pole jest wymagane");

            RuleFor(r => r.CategoryId)
                .NotEmpty()
                .WithMessage("Pole jest wymagane");
        }
    }
}

src/Project.Web/ViewModels/Product/ProductDetailsViewModel.cs
using FluentValidation;
using FluentValidation.Attributes;
using Project.Core.Infrastructure.AutoMapper;
using Project.Data.Models;
using System.ComponentModel.DataAnnotations;

namespace Project.Web.ViewModels.Product
{
    [Validator(typeof(ProductDetailsViewModelFluentValidator))]
    public class ProductDetailsViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        [Display(Name = "Cena")]
        public decimal Price { get; set; }

        [Display(Name= "Opis")]
        public string Description { get; set; }
                
        public int Count { get; set; }

        public string Path { get; set; }

        [Display(Name = "Ilość")]
        public int BuyQuantity { get; set; } = 1;
    }

    public class ProductDetailsViewModelProfile : AutoMapperProfile
    {
        public ProductDetailsViewModelProfile()
        {
            CreateMap<ProductModel, ProductDetailsViewModel>();

            CreateMap<ProductDetailsViewModel, ProductModel>()
                .ForMember(desc => desc.Count, src => src.MapFrom(u => u.BuyQuantity));
        }
    }

    public class ProductDetailsViewModelFluentValidator : AbstractValidator<ProductDetailsViewModel>
    {
        public ProductDetailsViewModelFluentValidator()
        {
            RuleFor(r => r.BuyQuantity)
                .NotEmpty()
                .WithMessage("Pole jest wymagane")
                .GreaterThan(0)
                .WithMessage("Wartość musi być większa od zera");
        }
    }
}

src/Project.Web/ViewModels/Product/ProductIndexRowViewModel.cs
using Project.Core.Infrastructure.AutoMapper;
using Project.Data.Models;
using System.Collections.Generic;

namespace Project.Web.ViewModels.Product
{
    public class ProductIndexViewModel
    {
        public IEnumerable<ProductIndexRowViewModel> Products { get; set; }
    }

    public class ProductIndexRowViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string PathResize { get; set; }
    }

    public class ProductIndexViewModelProfile : AutoMapperProfile
    {
        public ProductIndexViewModelProfile()
        {
            CreateMap<ProductModel, ProductIndexRowViewModel>();
        }
    }
}

src/Project.Web/Controllers/CartController.cs
using AutoMapper;
using Project.Data.Models;
using Project.Service.Services;
using Project.Web.TemporaryMessage;
using Project.Web.ViewModels.Cart;
using Project.Web.ViewModels.Product;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class CartController : BaseController
    {
        private readonly ICartService _cartService;

        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }

        [HttpGet]
        [Authorize]
        public PartialViewResult Index()
        {
            var data =
                new CartIndexViewModel
                {
                    Carts =
                        Mapper.Map<List<CartIndexRowViewModel>>(
                            _cartService
                                .GetCartItems())
                };

            return PartialView("_Index", data.Carts);
        }


        [HttpPost]
        [Authorize]
        public ActionResult Create(ProductDetailsViewModel productDetailsViewModel)
        {
            var productModel = Mapper.Map<ProductModel>(productDetailsViewModel);

            _cartService.Create(productModel);

            SetTemporaryMessage(CartMessage.CartAdded, TemporaryType.Succes);

            return RedirectToAction("Index", "Product");
        }


        [HttpPost]
        [Authorize]
        public PartialViewResult Delete (int id)
        {
            _cartService.Delete(id);

            return Index();
        }
    }
}

src/Project.Web/Controllers/CategoryController.cs
using Project.Data.Models;
using Project.Service.Services;
using Project.Web.ViewModels.Category;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var data = GetTreeCategory();
            return PartialView("_Index",data);
        }

        public List<CategoryIndexViewModel> GetTreeCategory() =>
            FillRecursive(_categoryService.GetCategories(), null);

        private List<CategoryIndexViewModel> FillRecursive(List<CategoryModel> categories, int? parentId = null) =>
            categories
                .Where(x => x.ParentId.Equals(parentId))
                .Select(item => new CategoryIndexViewModel
                {
                    Name = item.Name,
                    Id = item.Id.Value,
                    Children = FillRecursive(categories, item.Id)
                })
                .ToList();
    }
}

src/Project.Web/Controllers/ProductController.cs
using AutoMapper;
using Project.Data.Models;
using Project.Service.Helper.Serilog;
using Project.Service.Services;
using Project.Web.Infrastructure.Role;
using Project.Web.TemporaryMessage;
using Project.Web.ViewModels.Product;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly ILogService _logService;

        public ProductController(
            ICategoryService categoryService,
            IProductService productService,
            ILogService logService)
        {
            _categoryService = categoryService;
            _productService = productService;
            _logService = logService;
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Index(int? categoryId)
        {
            IEnumerable<ProductModel> products;

            if(categoryId == null)
                products =
                    _productService
                        .GetProducts();
            else
            {
                var categories =
                    _categoryService
                        .GetCategories();

                var childrenCategoriesId =
                    _categoryService
                        .GetChildrenCategoriesId(
                            categories,
                            categoryId.Value);

                childrenCategoriesId.Add(categoryId.Value);

                products =
                    _productService
                        .GetProductsBy(childrenCategoriesId);
            }

            var data = new ProductIndexViewModel
            {
                Products = Mapper.Map<List<ProductIndexRowViewModel>>(products)
            };

            return View(data.Products);
        }

        [Authorize(Roles = AppRoles.Admin)]
        [HttpGet]
        public ActionResult Create()
        {
            var data = new ProductCreateViewModel
            {
                Category = _categoryService.GetCategories()
            };

            data.Category.Insert(0, new CategoryModel
            {
                Id = null,
                Name = string.Empty
            });

            return View(data);
        }

        [HttpPost]
        public ActionResult Create(ProductCreateViewModel createViewModel, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                var prodcutModel = Mapper.Map<ProductModel>(createViewModel);

                var product =
                    _productService
                        .Create(prodcutModel, Image);

                SetTemporaryMessage(ProductMessage.ProductAdded, TemporaryType.Succes);
                _logService.Logger.Information("Dodano product : {@product}", product);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var data =
                Mapper.Map<ProductDetailsViewModel>(
                    _productService
                        .GetProductBy(id.Value));

            return View(data);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Details(ProductDetailsViewModel productDetailsViewModel)
        {
            if (!ModelState.IsValid)
            {
                var data =
                Mapper.Map<ProductDetailsViewModel>(
                    _productService
                        .GetProductBy(productDetailsViewModel.Id));
                return View(data);

            }

            return View();
        }
    }
}

src/Project.Web/Views/Product/Create.cshtml
@model Project.Web.ViewModels.Product.ProductCreateViewModel

@{
    ViewBag.Title = "Create";
}
<div class="text-center">
    <h2>Dodawanie Produktu</h2>
</div>

@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    @Html.AntiForgeryToken()

    <div class="form-horizontal container">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-8 col-md-offset-3 ">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-3 ">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @Value = "" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-3 ">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-3 ">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control", @type = "file"} })

                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-3 ">
                @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control", @Value = "" } })
                    @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-3 ">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.Category, "Id", "Name"), htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-offset-4point5">
            <div class="form-group ">
                <div class="row col-md-6 ">

                    <div class="col-xs-3">
                        <input type="submit" value="Zapisz" class="btn btn-success" />
                    </div>
                    <div class="col-xs-3">
                        <input type="button" value="Powrót" class="btn btn-info" onclick="location.href='@Url.Action("Index", "Product")'" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

src/Project.Web/Views/Product/Details.cshtml
@model Project.Web.ViewModels.Product.ProductDetailsViewModel
@{
    ViewBag.Title = "Details";
}

@Styles.Render("~/Content/css/app/product/details.css")
@Scripts.Render("~/Scripts/app/views/product/details/details.js")

@using (Html.BeginForm("Create","Cart", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.Id)

    <div class="container">
        <div class="row">
            <div class="col-md-6 image">
                <img src="@Model.Path.Remove(0, Model.Path.IndexOf(@"\Content"))"
                     style="height: 100%; width: 100%; object-fit: contain">
            </div>
            <div class="col-md-6">
                <div class="row col-lg-10 col-xs-offset-1 title">
                    @Model.Name
                </div>
                <div class="row col-lg-10 col-xs-offset-1 count">
                    <h2>
                        Pozostało: @Model.Count sztuk
                    </h2>
                </div>
                <div class="row col-lg-10 col-xs-offset-1">
                    <div class="col-md-7 ">
                        <div class="row">
                            @Html.LabelFor(model => model.BuyQuantity, htmlAttributes: new { @class = "control-label h3" })
                        </div>
                        <div class="row ">
                            <button id="btnPlus" type="button" class="btn btn-success btn-number">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>
                            @Html.EditorFor(model => model.BuyQuantity, new { htmlAttributes = new { @class = "col-md-3 form-control buyQuantity" } })
                            <button id="btnMinus" type="button" class="btn btn-danger btn-number">
                                <span class="glyphicon glyphicon-minus"></span>
                            </button>

                        </div>
                        <div class="row">
                            @Html.ValidationMessageFor(model => model.BuyQuantity, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <div class="row col-lg-10 col-xs-offset-1">
                        <input type="submit" value="Dodaj do koszyka" class="btn-addCard" />
                    </div>
                }
            </div>
        </div>
        <div class="row menu">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label h3" })
            </div>
        </div>
        <div class="row h3">
            @Html.DisplayTextFor(model => model.Description)
        </div>
    </div>
}

src/Project.Web/Views/Product/Index.cshtml
@model IEnumerable<Project.Web.ViewModels.Product.ProductIndexRowViewModel>
@{
    ViewBag.Title = "Index";
}
@{ var count = 1; }

<div class="row">
    <div class="col-md-3">
        @Html.Action("Index", "Category")
    </div>

    <div class="col-md-8 ">
        <div class="row">
            @foreach (var item in Model)
            {
                if (count % 3 == 0)
                {
                    @:<div class="row">
                }
                <div class="col-lg-4 col-sm-6">
                    <div class="card h-100">
                        <img class="card-img-top"
                                src="@item.PathResize.Remove(0,item.PathResize.IndexOf(@"\Content"))"
                                alt=""
                                style="height: 100%; width: 100%; object-fit: contain">
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="@Url.Action("Details", new { id = item.Id})">@item.Name</a>
                            </h4>
                        </div>
                    </div>
                </div>
                if (count % 3 == 0)
                {
                    @:</div>
                }
                count++;
            }
        </div>
    </div>
</div>

@Scripts.Render("~/Scripts/app/views/product/index/index.js")