src/Project.Web/ViewModels/Cart/CartCreateModel.cs
using Project.Core.Infrastructure.AutoMapper;
using Project.Data.Models;
using System;

namespace Project.Web.ViewModels.Cart
{
    public class CartCreateModel
    {
        public int ProductId { get; set; }

        public int UserId { get; set; }

        public int Count { get; set; }

        public DateTime InsertTime { get; set; }
    }

    public class CartCreateModelProfile : AutoMapperProfile
    {
        public CartCreateModelProfile()
        {
            CreateMap<CartCreateModel, CartModel>();
        }
    }
}

src/Project.Web/ViewModels/Cart/CartIndexViewModel.cs
using Project.Core.Infrastructure.AutoMapper;
using Project.Data.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Project.Web.ViewModels.Cart
{
    public class CartIndexViewModel
    {
        public IEnumerable<CartIndexRowViewModel> Carts { get; set; }
    }

    public class CartIndexRowViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Zdjęcie")]
        public string PathResize { get; set; }

        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [Display(Name = "Cena")]
        public decimal Price { get; set; }

        [Display(Name = "Ilość")]
        public int Count { get; set; }
    }

    public class CartIndexViewModelProfile : AutoMapperProfile
    {
        public CartIndexViewModelProfile()
        {
            CreateMap<CartModel, CartIndexRowViewModel>();
        }
    }
}

src/Project.Web/Controllers/CartController.cs
using AutoMapper;
using Project.Data.Models;
using Project.Service.Services;
using Project.Web.TemporaryMessage;
using Project.Web.ViewModels.Cart;
using Project.Web.ViewModels.Product;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class CartController : BaseController
    {
        private readonly ICartService _cartService;

        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }

        [HttpGet]
        [Authorize]
        public PartialViewResult Index()
        {
            var data =
                new CartIndexViewModel
                {
                    Carts =
                        Mapper.Map<List<CartIndexRowViewModel>>(
                            _cartService
                                .GetCartItems())
                };

            return PartialView("_Index", data.Carts);
        }


        [HttpPost]
        [Authorize]
        public ActionResult Create(ProductDetailsViewModel productDetailsViewModel)
        {
            var productModel = Mapper.Map<ProductModel>(productDetailsViewModel);

            _cartService.Create(productModel);

            SetTemporaryMessage(CartMessage.CartAdded, TemporaryType.Succes);

            return RedirectToAction("Index", "Product");
        }


        [HttpPost]
        [Authorize]
        public PartialViewResult Delete (int id)
        {
            _cartService.Delete(id);

            return Index();
        }
    }
}

src/Project.Web/Controllers/OrderController.cs
using Project.Service.Helper.Serilog;
using Project.Service.Services;
using Project.Web.TemporaryMessage;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IOrderService _orderService;
        private readonly ILogService _logService;
        private readonly ICartService _cartService;

        public OrderController(
            IOrderService orderService,
            ILogService logService,
            ICartService cartService)
        {
            _orderService = orderService;
            _logService = logService;
            _cartService = cartService;
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create()
        {
            var cardItems =
                _cartService
                    .GetCartItems();

            if (cardItems.Count == 0)
                SetTemporaryMessage(OrderMessage.CartEmpty, TemporaryType.Warning);

            else
            {
                int id = _orderService.Create(cardItems);

                SetTemporaryMessage(OrderMessage.AddOrder, TemporaryType.Succes);
               _logService.Logger.Information("Zrealizowano zamówienie o id : {@}", id);             
            }

            return RedirectToAction("Index", "Product");
        }
    }
}

src/Project.Web/Views/Cart/_Index.cshtml
@model IEnumerable<Project.Web.ViewModels.Cart.CartIndexRowViewModel>

@using (Html.BeginForm("Create", "Order"))
{
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Koszyk
                </h4>
            </div>
            <div class="modal-body">
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.PathResize)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Count)
                        </th>
                        <th>

                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr id="@item.Id">
                            <td>
                                <img src="@item.PathResize.Remove(0, item.PathResize.IndexOf(@"\Content"))" width="50" height="50" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Count)
                            </td>
                            <td>
                                @Html.ActionLink("Usuń", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                    }

                </table>
                <button type="submit" class="btn btn-primary">
                    Zatwierdź
                </button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">
                    Zamknij
                </button>
            </div>
        </div>
    </div>
}